import "@/styles/globals.css";

import { ReactNode } from "react";
import { Inter } from "next/font/google";

const inter = Inter({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Pedro Augusto",
    template: "%s | Pedro Augusto",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} w-screen h-screen bg-app flex justify-center items-center`}
      >
        {children}
      </body>
    </html>
  );
}
